export const resumeThemes = {
  modern: {
    id: "modern",
    name: "Modern Professional",
    description: "Clean and contemporary design for corporate roles",
    category: "Professional",
    color: "#6366f1",
    gradient: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
    styles: {
      header: {
        background: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
        color: "#ffffff",
        padding: "2rem",
        textAlign: "center",
      },
      name: {
        fontSize: "2.5rem",
        fontWeight: 700,
        marginBottom: "0.5rem",
        color: "#ffffff",
      },
      title: {
        fontSize: "1.25rem",
        fontWeight: 500,
        color: "#e2e8f0",
        marginBottom: "1rem",
      },
      contact: {
        display: "flex",
        justifyContent: "center",
        gap: "2rem",
        flexWrap: "wrap",
        color: "#e2e8f0",
        fontSize: "0.9rem",
      },
      section: {
        marginBottom: "2rem",
        padding: "0 2rem",
      },
      sectionTitle: {
        fontSize: "1.5rem",
        fontWeight: 600,
        color: "#6366f1",
        borderBottom: "2px solid #6366f1",
        paddingBottom: "0.5rem",
        marginBottom: "1rem",
      },
      item: {
        marginBottom: "1.5rem",
        paddingLeft: "1rem",
        borderLeft: "3px solid #6366f1",
      },
      itemTitle: {
        fontSize: "1.1rem",
        fontWeight: 600,
        color: "#1e293b",
        marginBottom: "0.25rem",
      },
      itemSubtitle: {
        fontSize: "1rem",
        fontWeight: 500,
        color: "#6366f1",
        marginBottom: "0.25rem",
      },
      itemDate: {
        fontSize: "0.9rem",
        color: "#64748b",
        fontStyle: "italic",
        marginBottom: "0.5rem",
      },
      itemDescription: {
        fontSize: "0.95rem",
        color: "#475569",
        lineHeight: 1.6,
      },
      skills: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.5rem",
      },
      skill: {
        backgroundColor: "#6366f1",
        color: "#ffffff",
        padding: "0.5rem 1rem",
        borderRadius: "20px",
        fontSize: "0.9rem",
        fontWeight: 500,
      },
    },
  },
  creative: {
    id: "creative",
    name: "Creative Portfolio",
    description: "Bold and artistic design for creative professionals",
    category: "Creative",
    color: "#ec4899",
    gradient: "linear-gradient(135deg, #ec4899 0%, #f97316 100%)",
    styles: {
      header: {
        background: "linear-gradient(135deg, #ec4899 0%, #f97316 100%)",
        color: "#ffffff",
        padding: "3rem 2rem",
        textAlign: "center",
        position: "relative",
        overflow: "hidden",
      },
      name: {
        fontSize: "3rem",
        fontWeight: 800,
        marginBottom: "0.5rem",
        color: "#ffffff",
        textTransform: "uppercase",
        letterSpacing: "2px",
      },
      title: {
        fontSize: "1.5rem",
        fontWeight: 400,
        color: "#fecaca",
        marginBottom: "1.5rem",
        fontStyle: "italic",
      },
      contact: {
        display: "flex",
        justifyContent: "center",
        gap: "2rem",
        flexWrap: "wrap",
        color: "#fecaca",
        fontSize: "1rem",
      },
      section: {
        marginBottom: "2.5rem",
        padding: "0 2rem",
      },
      sectionTitle: {
        fontSize: "1.75rem",
        fontWeight: 700,
        color: "#ec4899",
        textTransform: "uppercase",
        letterSpacing: "1px",
        marginBottom: "1.5rem",
        position: "relative",
        "&::after": {
          content: '""',
          position: "absolute",
          bottom: "-0.5rem",
          left: 0,
          width: "3rem",
          height: "3px",
          backgroundColor: "#ec4899",
        },
      },
      item: {
        marginBottom: "2rem",
        padding: "1.5rem",
        backgroundColor: "#fef7ff",
        borderRadius: "12px",
        border: "1px solid #fce7f3",
      },
      itemTitle: {
        fontSize: "1.25rem",
        fontWeight: 700,
        color: "#ec4899",
        marginBottom: "0.5rem",
      },
      itemSubtitle: {
        fontSize: "1.1rem",
        fontWeight: 600,
        color: "#f97316",
        marginBottom: "0.5rem",
      },
      itemDate: {
        fontSize: "0.9rem",
        color: "#9ca3af",
        fontStyle: "italic",
        marginBottom: "0.75rem",
      },
      itemDescription: {
        fontSize: "1rem",
        color: "#4b5563",
        lineHeight: 1.7,
      },
      skills: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.75rem",
      },
      skill: {
        background: "linear-gradient(135deg, #ec4899 0%, #f97316 100%)",
        color: "#ffffff",
        padding: "0.75rem 1.5rem",
        borderRadius: "25px",
        fontSize: "1rem",
        fontWeight: 600,
        boxShadow: "0 4px 12px rgba(236, 72, 153, 0.3)",
      },
    },
  },
  minimal: {
    id: "minimal",
    name: "Minimal Clean",
    description: "Simple and elegant design focusing on content",
    category: "Minimal",
    color: "#1e293b",
    gradient: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
    styles: {
      header: {
        background: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
        color: "#ffffff",
        padding: "2.5rem 2rem",
        textAlign: "center",
      },
      name: {
        fontSize: "2.25rem",
        fontWeight: 300,
        marginBottom: "0.5rem",
        color: "#ffffff",
        letterSpacing: "1px",
      },
      title: {
        fontSize: "1.1rem",
        fontWeight: 400,
        color: "#cbd5e1",
        marginBottom: "1rem",
        letterSpacing: "0.5px",
      },
      contact: {
        display: "flex",
        justifyContent: "center",
        gap: "2rem",
        flexWrap: "wrap",
        color: "#cbd5e1",
        fontSize: "0.9rem",
        letterSpacing: "0.5px",
      },
      section: {
        marginBottom: "2rem",
        padding: "0 2rem",
      },
      sectionTitle: {
        fontSize: "1.25rem",
        fontWeight: 500,
        color: "#1e293b",
        marginBottom: "1.5rem",
        textTransform: "uppercase",
        letterSpacing: "1px",
        borderBottom: "1px solid #e2e8f0",
        paddingBottom: "0.5rem",
      },
      item: {
        marginBottom: "1.5rem",
        paddingBottom: "1.5rem",
        borderBottom: "1px solid #f1f5f9",
      },
      itemTitle: {
        fontSize: "1.1rem",
        fontWeight: 500,
        color: "#1e293b",
        marginBottom: "0.25rem",
      },
      itemSubtitle: {
        fontSize: "1rem",
        fontWeight: 400,
        color: "#475569",
        marginBottom: "0.25rem",
      },
      itemDate: {
        fontSize: "0.85rem",
        color: "#94a3b8",
        marginBottom: "0.5rem",
      },
      itemDescription: {
        fontSize: "0.95rem",
        color: "#64748b",
        lineHeight: 1.6,
      },
      skills: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.5rem",
      },
      skill: {
        backgroundColor: "#f8fafc",
        color: "#1e293b",
        padding: "0.5rem 1rem",
        borderRadius: "4px",
        fontSize: "0.9rem",
        fontWeight: 400,
        border: "1px solid #e2e8f0",
      },
    },
  },
  academic: {
    id: "academic",
    name: "Academic Scholar",
    description: "Formal design perfect for research and education",
    category: "Academic",
    color: "#059669",
    gradient: "linear-gradient(135deg, #059669 0%, #047857 100%)",
    styles: {
      header: {
        background: "linear-gradient(135deg, #059669 0%, #047857 100%)",
        color: "#ffffff",
        padding: "2rem",
        textAlign: "center",
      },
      name: {
        fontSize: "2.5rem",
        fontWeight: 600,
        marginBottom: "0.5rem",
        color: "#ffffff",
      },
      title: {
        fontSize: "1.25rem",
        fontWeight: 400,
        color: "#d1fae5",
        marginBottom: "1rem",
      },
      contact: {
        display: "flex",
        justifyContent: "center",
        gap: "2rem",
        flexWrap: "wrap",
        color: "#d1fae5",
        fontSize: "0.9rem",
      },
      section: {
        marginBottom: "2rem",
        padding: "0 2rem",
      },
      sectionTitle: {
        fontSize: "1.5rem",
        fontWeight: 600,
        color: "#059669",
        marginBottom: "1rem",
        borderBottom: "2px solid #059669",
        paddingBottom: "0.5rem",
      },
      item: {
        marginBottom: "1.5rem",
        paddingLeft: "1.5rem",
        borderLeft: "4px solid #059669",
      },
      itemTitle: {
        fontSize: "1.2rem",
        fontWeight: 600,
        color: "#1e293b",
        marginBottom: "0.25rem",
      },
      itemSubtitle: {
        fontSize: "1.1rem",
        fontWeight: 500,
        color: "#059669",
        marginBottom: "0.25rem",
      },
      itemDate: {
        fontSize: "0.9rem",
        color: "#64748b",
        fontStyle: "italic",
        marginBottom: "0.5rem",
      },
      itemDescription: {
        fontSize: "1rem",
        color: "#475569",
        lineHeight: 1.6,
      },
      skills: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.5rem",
      },
      skill: {
        backgroundColor: "#059669",
        color: "#ffffff",
        padding: "0.5rem 1rem",
        borderRadius: "4px",
        fontSize: "0.9rem",
        fontWeight: 500,
      },
    },
  },
  tech: {
    id: "tech",
    name: "Tech Developer",
    description: "Modern design for software and tech professionals",
    category: "Technology",
    color: "#0ea5e9",
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #3b82f6 100%)",
    styles: {
      header: {
        background: "linear-gradient(135deg, #0ea5e9 0%, #3b82f6 100%)",
        color: "#ffffff",
        padding: "2.5rem 2rem",
        textAlign: "center",
      },
      name: {
        fontSize: "2.5rem",
        fontWeight: 700,
        marginBottom: "0.5rem",
        color: "#ffffff",
        fontFamily: "'Courier New', monospace",
      },
      title: {
        fontSize: "1.25rem",
        fontWeight: 400,
        color: "#bae6fd",
        marginBottom: "1rem",
        fontFamily: "'Courier New', monospace",
      },
      contact: {
        display: "flex",
        justifyContent: "center",
        gap: "2rem",
        flexWrap: "wrap",
        color: "#bae6fd",
        fontSize: "0.9rem",
        fontFamily: "'Courier New', monospace",
      },
      section: {
        marginBottom: "2rem",
        padding: "0 2rem",
      },
      sectionTitle: {
        fontSize: "1.5rem",
        fontWeight: 600,
        color: "#0ea5e9",
        marginBottom: "1rem",
        fontFamily: "'Courier New', monospace",
        borderBottom: "2px solid #0ea5e9",
        paddingBottom: "0.5rem",
      },
      item: {
        marginBottom: "1.5rem",
        padding: "1rem",
        backgroundColor: "#f0f9ff",
        borderRadius: "8px",
        border: "1px solid #e0f2fe",
      },
      itemTitle: {
        fontSize: "1.2rem",
        fontWeight: 600,
        color: "#0ea5e9",
        marginBottom: "0.25rem",
        fontFamily: "'Courier New', monospace",
      },
      itemSubtitle: {
        fontSize: "1.1rem",
        fontWeight: 500,
        color: "#3b82f6",
        marginBottom: "0.25rem",
      },
      itemDate: {
        fontSize: "0.9rem",
        color: "#64748b",
        fontStyle: "italic",
        marginBottom: "0.5rem",
      },
      itemDescription: {
        fontSize: "1rem",
        color: "#475569",
        lineHeight: 1.6,
      },
      skills: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.5rem",
      },
      skill: {
        backgroundColor: "#0ea5e9",
        color: "#ffffff",
        padding: "0.5rem 1rem",
        borderRadius: "6px",
        fontSize: "0.9rem",
        fontWeight: 500,
        fontFamily: "'Courier New', monospace",
      },
    },
  },
  elegant: {
    id: "elegant",
    name: "Elegant Classic",
    description: "Timeless design with sophisticated styling",
    category: "Classic",
    color: "#7c3aed",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #a855f7 100%)",
    styles: {
      header: {
        background: "linear-gradient(135deg, #7c3aed 0%, #a855f7 100%)",
        color: "#ffffff",
        padding: "3rem 2rem",
        textAlign: "center",
      },
      name: {
        fontSize: "3rem",
        fontWeight: 300,
        marginBottom: "0.5rem",
        color: "#ffffff",
        fontFamily: "Georgia, serif",
      },
      title: {
        fontSize: "1.5rem",
        fontWeight: 400,
        color: "#e9d5ff",
        marginBottom: "1.5rem",
        fontFamily: "Georgia, serif",
        fontStyle: "italic",
      },
      contact: {
        display: "flex",
        justifyContent: "center",
        gap: "2rem",
        flexWrap: "wrap",
        color: "#e9d5ff",
        fontSize: "1rem",
        fontFamily: "Georgia, serif",
      },
      section: {
        marginBottom: "2.5rem",
        padding: "0 2rem",
      },
      sectionTitle: {
        fontSize: "1.75rem",
        fontWeight: 400,
        color: "#7c3aed",
        marginBottom: "1.5rem",
        fontFamily: "Georgia, serif",
        borderBottom: "1px solid #7c3aed",
        paddingBottom: "0.5rem",
        textAlign: "center",
      },
      item: {
        marginBottom: "2rem",
        padding: "1.5rem",
        backgroundColor: "#faf5ff",
        borderRadius: "12px",
        border: "1px solid #f3e8ff",
      },
      itemTitle: {
        fontSize: "1.3rem",
        fontWeight: 500,
        color: "#7c3aed",
        marginBottom: "0.5rem",
        fontFamily: "Georgia, serif",
      },
      itemSubtitle: {
        fontSize: "1.1rem",
        fontWeight: 400,
        color: "#a855f7",
        marginBottom: "0.5rem",
        fontStyle: "italic",
      },
      itemDate: {
        fontSize: "0.9rem",
        color: "#8b5cf6",
        fontStyle: "italic",
        marginBottom: "0.75rem",
      },
      itemDescription: {
        fontSize: "1rem",
        color: "#4c1d95",
        lineHeight: 1.7,
      },
      skills: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.75rem",
      },
      skill: {
        background: "linear-gradient(135deg, #7c3aed 0%, #a855f7 100%)",
        color: "#ffffff",
        padding: "0.75rem 1.5rem",
        borderRadius: "20px",
        fontSize: "1rem",
        fontWeight: 400,
        fontFamily: "Georgia, serif",
        boxShadow: "0 4px 12px rgba(124, 58, 237, 0.3)",
      },
    },
  },
};

export const getThemeById = (themeId) => {
  return resumeThemes[themeId] || resumeThemes.modern;
};

export const getAllThemes = () => {
  return Object.values(resumeThemes);
};
